language: java

jdk:
- oraclejdk8
- openjdk8
- openjdk10
- openjdk11

after_success:
- bash <(curl -s https://codecov.io/bash)

before_deploy:
  - travis_wait 1200 "mvn -DskipTests package"

deploy:
  provider: releases
  on:
    tags: true
    jdk: oraclejdk8
