language: java

jdk:
- oraclejdk8

after_success:
- bash < (curl -s https://codecov.io/bash)

before_deploy:
  - "mvn -DskipTests package"

env:
 global:
   - CODECOV_TOKEN: ab1fc27b-2178-4815-a4a8-433ed4e8aef2

deploy:
  provider: releases
  on:
    tags: true
    jdk: oraclejdk8